import { RFValue } from "react-native-responsive-fontsize";
import { StyleSheet, Dimensions } from "react-native";
const WIDTH = Dimensions.get("window").width;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F1F9FF",
  },
  topContainer: {
    backgroundColor: "#FFFFFF",
    maxWidth: RFValue(400),
    width: WIDTH - RFValue(20),
    height: RFValue(200),
    flexDirection: "column",
    justifyContent: "space-around",
    alignItems: "center",
    borderRadius: 8,
  },
  titleTop: {
    width: RFValue(250),
    alignSelf: "flex-start",
    paddingLeft: 30,
    fontWeight: "700",
    fontSize: 22,
  },
  mainButton: {
    width: "85%",
    height: 55,
    flexDirection: "row",
    backgroundColor: "background: rgba(21, 49, 68, 1)",
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: 10,
    paddingHorizontal: 30,
  },
  textButton: {
    color: "white",
    fontSize: 14,
    fontWeight: "500",
  },
  servicesContainer: {
    width: "90%",
    alignItems: "center",
  },
  servicesButtonVeicular: {
    flexDirection: "row",
    width: "90%",
    maxWidth: 400,
    height: 70,
    backgroundColor: "background: rgba(44, 151, 255, 1)",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 15,
    paddingLeft: 30,
    paddingRight: 30,
    marginTop: 30,
  },
  servicesButtonCasa: {
    flexDirection: "row",
    width: "90%",
    height: 70,
    maxWidth: 400,
    backgroundColor: "rgba(0, 115, 226, 1)",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 15,
    paddingLeft: 30,
    paddingRight: 30,
    marginTop: 10,
  },
  servicesButtonVida: {
    flexDirection: "row",
    width: "90%",
    height: 70,
    maxWidth: 400,
    backgroundColor: "rgba(0, 77, 153, 1)",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 15,
    paddingLeft: 30,
    paddingRight: 30,
    marginTop: 10,
  },
  servicesButtonPrivada: {
    flexDirection: "row",
    width: "90%",
    maxWidth: 400,
    height: 70,
    backgroundColor: "rgba(0, 37, 73, 1)",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 15,
    paddingLeft: 30,
    paddingRight: 30,
    marginTop: 10,
  },
  topWarning: {
    width: WIDTH - RFValue(40),
    maxWidth: 400,
    backgroundColor: "#2C97FF",
    borderRadius: 15,
    flexDirection:"row",
    justifyContent:"space-around",
    alignItems:"center",
    paddingVertical:20,
    marginTop:RFValue(40),
    marginBottom:RFValue(20)
  },
  textWarning:{
   width:"60%",
   color:"white",
   fontSize:15
  }
});
